accounts:
    resource: ../../src/Module/AccountCentre/Controller/
    type: attribute

admin:
    resource: ../../src/Module/Admin/Controller/
    type: attribute

auth:
    resource: ../../src/Module/Auth/Controller/
    type: attribute

social:
    resource: ../../src/Module/Social/Controller/
    type: attribute

main:
    resource: ../../src/Module/Main/Controller/
    type: attribute

org:
    resource: ../../src/Module/Org/Controller/
    type: attribute
